// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// Tool is an autogenerated mock type for the Tool type
type Tool struct {
	mock.Mock
}

// AddTool provides a mock function with given fields: w, r
func (_m *Tool) AddTool(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// EditTool provides a mock function with given fields: w, r
func (_m *Tool) EditTool(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// GetAllTools provides a mock function with given fields: w, r
func (_m *Tool) GetAllTools(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RemoveTool provides a mock function with given fields: w, r
func (_m *Tool) RemoveTool(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewTool creates a new instance of Tool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTool(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tool {
	mock := &Tool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
